### ISSUE TITLE
GMod Crashes After Ranged Kill

### ISSUE THREAD

**Issue by CombineSlayer24** [Emana202/Lambda-Players-TF2-Weapons#3]
Lately, I noticed when a Lambdaplayer uses a TF2 ranged weapon, like Shotguns or Rocket Luanchers for example, the game will crash after the Lambdaplayer gets a kill. The crash is somewhat inconsistent when it happens, it happens after like 6, 13 kills. I've switched between both the default and x64-x86 branches, nothing. I have no idea why it's causing crashes.

```
-Lua Stack Traces-
==================
  Client
    *Not in Lua call OR Lua has panicked*

  Server
    0. DispatchTraceAttack - [C]:-1
      1. func - addons/lambda-players-tf2-weapons-main/lua/lambdaplayers/extaddon/server/lambda_tf2_weaponfuncs.lua:384
        2. (null) - addons/lambda-players-master/lua/lambdaplayers/lambda/sh_util.lua:159

  MenuSystem
    *Not in Lua call OR Lua has panicked*
```

**Comment by Emana202** [comment]
Strange, that code in the dump only runs when Lambda uses a melee weapon and hits or misses it

**Comment by CombineSlayer24** [comment]
I should have mentioned that I'm using a fork that adds some MvM Weapons and the only code addition added is "SpawnWithFullCharge" attribute recreation. https://github.com/CombineSlayer24/Lambda-Players-TF2-Weapons/commit/c4a5374f4bbd8020f7296f6effa35ac29f2c6925

I highly doubt that my fork causes the crashes since I switched between my fork and your version. It's very strange.
